### ISSUE TITLE
Stats' page graphs are not generating

### ISSUE THREAD

**Issue by chris-griffin** [whoishiring/feedback#6]
![image](https://cloud.githubusercontent.com/assets/1795659/17078292/d72485b6-50bc-11e6-9f54-e538df9f20b0.png)

On Windows / Chrome Version 52.0.2743.82 m

Thanks for putting this project together! Here is the JS console error:

main.bundle.js:1705TypeError: Cannot read property 'labels' of undefined
    at https://whoishiring.io/build/main.bundle.js:1:19037
    at https://whoishiring.io/build/main.bundle.js:2:17448
    at s (https://whoishiring.io/build/main.bundle.js:2:35159)
    at https://whoishiring.io/build/main.bundle.js:2:35331
    at h.$eval (https://whoishiring.io/build/main.bundle.js:2:42848)
    at h.$digest (https://whoishiring.io/build/main.bundle.js:2:41356)
    at h.$apply (https://whoishiring.io/build/main.bundle.js:2:43131)
    at o (https://whoishiring.io/build/main.bundle.js:2:17981)
    at g (https://whoishiring.io/build/main.bundle.js:2:19829)
    at XMLHttpRequest.w.onload (https://whoishiring.io/build/main.bundle.js:2:20372)
    at XMLHttpRequest.n (https://whoishiring.io/build/main.bundle.js:38:3790) undefined

**Comment by xando** [comment]
Thanks for the report. 

Fixed and deployed.
